--?? 1. Script Oracle 19c
CREATE TABLE DOCUMENTOS_WORD (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(200),
    ARCHIVO BLOB,
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

COMMIT;